services:
  airflow_service:
    build: ./airflow_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./airflow_service/:/app/
    ports:
      - 8001:8000
    env_file:
      - .env
    environment:
      - DATABASE_URI=postgresql://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}/${AIRFLOW_DB}
      - AIRFLOW_SERVICE_HOST_URL=http://airflow_service:8000/api/v1/airflow/
    depends_on:
      - airflow_db

  airflow_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_airflow:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${AIRFLOW_DB_USER}
      - POSTGRES_PASSWORD=${AIRFLOW_DB_PASSWORD}
      - POSTGRES_DB=${AIRFLOW_DB}

  provider_a_service:
    build: ./provider_a_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./provider_a_service/:/app/
    ports:
      - 8002:8000
    env_file:
      - .env
    environment:
      - DATABASE_URI=postgresql://${PROVIDER_A_DB_USER}:${PROVIDER_A_DB_PASSWORD}@${PROVIDER_A_DB_HOST}/${PROVIDER_A_DB}
      - PROVIDER_A_SERVICE_HOST_URL=http://provider_a_service:8000/api/v1/provider_a/
    depends_on:
      - provider_a_service_db

  provider_a_service_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_provider_a:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PROVIDER_A_DB_USER}
      - POSTGRES_PASSWORD=${PROVIDER_A_DB_PASSWORD}
      - POSTGRES_DB=${PROVIDER_A_DB}
  
  provider_b_service:
    build: ./provider_b_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./provider_b_service/:/app/
    ports:
      - 8003:8000
    env_file:
      - .env
    environment:
      - DATABASE_URI=postgresql://${PROVIDER_B_DB_USER}:${PROVIDER_B_DB_PASSWORD}@${PROVIDER_B_DB_HOST}/${PROVIDER_B_DB}
      - PROVIDER_B_SERVICE_HOST_URL=http://provider_b_service:8000/api/v1/provider_b/
    depends_on:
      - provider_b_service_db

  provider_b_service_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_provider_b:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PROVIDER_B_DB_USER}
      - POSTGRES_PASSWORD=${PROVIDER_B_DB_PASSWORD}
      - POSTGRES_DB=${PROVIDER_B_DB}

volumes:
  postgres_data_airflow:
  postgres_data_provider_a:
  postgres_data_provider_b: