version: '3.7'

services:
  airflow_service:
    build: ./airflow-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./airflow-service/:/app/
    ports:
      - 8001:8000
    environment:
      - PROVIDER_A_HOST_URL=http://provider_a_service:8000/api/v1/providers_a
      - PROVIDER_B_HOST_URL=http://provider_b_service:8000/api/v1/providers_b
  
 
  provider_a_service:
    build: ./provider-a-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./provider-a-service/:/app/
    ports:
      - 8002:8000


  provider_b_service:
    build: ./provider-b-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./provider-b-service/:/app/
    ports:
      - 8003:8000


  nginx:
    image: nginx:latest
    ports:
      - "9000:9000"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - airflow_service
      - provider_a_service
      - provider_b_service